In [1]:
import pandas

In [2]:
pandas.__version__

'1.1.2'

# Python Crash Course

## Part One

In [3]:
1

1

In [4]:
1.0

1.0

In [5]:
type(1)

int

In [6]:
type(1.0)

float

In [7]:
1+1

2

In [8]:
1*3

3

In [9]:
1/2

0.5

In [10]:
2**4

16

In [11]:
4 % 2

0

In [12]:
5 % 2

1

In [13]:
2 + 3 * 5 + 5

22

In [14]:
(2 + 3) * (5 + 5)

50

In [15]:
name_of_var = 2

In [16]:
x=1
y=2

In [17]:
x+y

3

In [18]:
'string'

'string'

In [19]:
"double"

'double'

In [20]:
"I dont like that "

'I dont like that '

In [21]:
print("hello")

hello


In [22]:
"hello"

'hello'

In [23]:
print("My name is {}".format('Jose'))

My name is Jose


In [24]:
print("My name is {},my number is {}".format('Jose','10'))

My name is Jose,my number is 10


In [25]:
print("First:{x} Second {y}".format(x='XXX',y='YYY'))

First:XXX Second YYY


In [26]:
print("First:{y} Second {y}".format(x='XXX',y='YYY'))

First:YYY Second YYY


In [27]:
print("First:{y} Second {x}".format(x='XXX',y='YYY'))

First:YYY Second XXX


In [28]:
[1,2,3]

[1, 2, 3]

In [29]:
['a','b','c']

['a', 'b', 'c']

In [30]:
[1,'a']

[1, 'a']

In [31]:
mylist= ['a','b','c']

In [32]:
mylist[0]

'a'

In [33]:
mylist[2]

'c'

In [34]:
mylist[-1]

'c'

In [35]:
mylist[0] = 'new'

In [36]:
mylist

['new', 'b', 'c']

In [37]:
mylist.append('d')

In [38]:
mylist

['new', 'b', 'c', 'd']

In [39]:
mylist = [1,2,[100,200]]

In [40]:
mylist[2][1]

200

In [41]:
d = {'key' : 'value','key2':'value2'} #dictionary

In [42]:
d['key']

'value'

In [43]:
d['key2']

'value2'

In [44]:
print(d)

{'key': 'value', 'key2': 'value2'}


In [45]:
True

True

In [46]:
False

False

In [47]:
t=(1,2,3) #tuple

In [48]:
{1,2,3} #set

{1, 2, 3}

In [49]:
{1,1,1,1,2,2,2,3,3}

{1, 2, 3}

## Part Two

In [50]:
1 > 2

False

In [51]:
1 < 5

True

In [52]:
1 >= 4

False

In [53]:
1 <= 3

True

In [54]:
1 == 1

True

In [55]:
'a' == 'a'

True

In [56]:
'A' == 'a'

False

In [57]:
1 != 2

True

In [58]:
(1 == 1)

True

In [59]:
(1 == 1) and ('a' == 'a')

True

In [60]:
(1 == 2) and ('a' == 'a')

False

In [61]:
(1 == 2) or ('a' == 'a')

True

In [62]:
(1 == 1) and ('a' == 'a') and (3 == 3)

True

In [63]:
if 1 == 1:
    print('yea!')

yea!


In [64]:
if 1 == 2:
    print('yea!')

In [65]:
if 1==2:
    print('worked!')
else:
    print('nope!')

nope!


In [66]:
if 1==2:
    print('worked!')
elif 3==3:
    print('second cond true!')
else:
    print('nope!')

second cond true!


In [67]:
seq = [1,2,3,4,5]

In [68]:
for item in seq:
    print(item)

1
2
3
4
5


In [69]:
for item in seq:
    print('hi!')

hi!
hi!
hi!
hi!
hi!


In [70]:
for item in seq:
    print(item+item)

2
4
6
8
10


In [71]:
i=1
while i<5:
    print('i is {}'.format(i))
    i+=1

i is 1
i is 2
i is 3
i is 4


In [72]:
x = [1,2,3,4]

In [73]:
range(5)

range(0, 5)

In [74]:
list(range(5))

[0, 1, 2, 3, 4]

In [75]:
list(range(2,5))

[2, 3, 4]

In [76]:
for x in range(5):
    print('hi')

hi
hi
hi
hi
hi


In [77]:
x = [1,2,3,4,5]

In [78]:
out = []
for num in x:
    out.append(num**2)
    
print(out)    

[1, 4, 9, 16, 25]


In [79]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

## Part Three

In [80]:
#function

def my_func():
    print('hello')

In [81]:
my_func()

hello


In [82]:
my_func

<function __main__.my_func()>

In [83]:
def my_func(name):
    print('hello ' + name)

In [84]:
my_func('Jose')

hello Jose


In [85]:
def my_func(name='No name'):
    print('hello ' + name)

In [86]:
my_func('Jose')

hello Jose


In [87]:
my_func()

hello No name


In [88]:
def my_func(name):
    '''
    This print out the user name!
    '''
    print('hello ' + name)

In [89]:
def square(x):
    return x**2

In [90]:
result=square(5)

In [91]:
result

25

In [92]:
def square(x):
    print(x**2)

In [93]:
result

25

In [94]:
result

25

In [95]:
type(result)

int

In [96]:
def times_two(var):
    return var*2

In [97]:
times_two(10)

20

In [98]:
lambda var: var*2 

<function __main__.<lambda>(var)>

In [99]:
st = 'hello my name is Sam'

In [100]:
st.lower()

'hello my name is sam'

In [101]:
st.upper()

'HELLO MY NAME IS SAM'

In [102]:
st.split()

['hello', 'my', 'name', 'is', 'Sam']

In [103]:
tweet = 'Hello #sports'

In [104]:
tweet.split()

['Hello', '#sports']

In [105]:
tweet.split('#')

['Hello ', 'sports']

In [106]:
tweet.split('#')[-1]

'sports'

In [107]:
d = {'k1': 'v1','k2':'v2'}

In [108]:
d.keys()

dict_keys(['k1', 'k2'])

In [109]:
d.items()

dict_items([('k1', 'v1'), ('k2', 'v2')])

In [110]:
mylist = [1,2,3]

In [111]:
last = mylist.pop()

In [112]:
mylist

[1, 2]

In [113]:
last

3

In [114]:
mylist=[1,2,3]

In [115]:
first=mylist.pop(0)

In [116]:
mylist

[2, 3]

In [117]:
first

1

In [118]:
'x' in [1,2,3]

False

In [119]:
1 in [1,2,3]

True

In [120]:
2 in mylist

True

In [121]:
mylist

[2, 3]

# Numpy

In [122]:
import numpy as np

In [123]:
mylist=[1,2,3]

In [124]:
type(mylist)

list

In [125]:
np.array(mylist)

array([1, 2, 3])

In [126]:
mylist

[1, 2, 3]

In [127]:
myarr=np.array(mylist)

In [128]:
type(myarr)

numpy.ndarray

In [129]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [130]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [132]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [135]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [136]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [138]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [140]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [141]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [142]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [143]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [144]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [145]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [146]:
np.random.rand(1)

array([0.67535238])

In [147]:
np.random.rand(5,6)

array([[0.06175992, 0.60393788, 0.23498997, 0.11324973, 0.06911827,
        0.45935486],
       [0.36645929, 0.16103229, 0.24237822, 0.47657466, 0.33833618,
        0.92104848],
       [0.03170807, 0.24339857, 0.20818909, 0.74136037, 0.32071487,
        0.83850661],
       [0.73506927, 0.86617735, 0.51349446, 0.48117539, 0.80201434,
        0.35400474],
       [0.52310192, 0.77148286, 0.88858217, 0.02663406, 0.93682911,
        0.29836301]])

In [148]:
np.random.randn(10)

array([ 0.71369287, -1.37633731, -0.04924865, -0.48159822, -1.08087447,
       -3.1044089 , -0.83369904, -1.3376899 ,  1.40383819, -0.52468275])

In [150]:
np.random.randn(2,3)

array([[-0.200101  ,  0.82383153,  0.08208379],
       [ 0.70953848,  0.09051228,  0.65110157]])

In [152]:
np.random.randint(0,101,5)

array([49, 36, 21, 30, 28])

In [153]:
np.random.randint(0,101,(4,5))

array([[ 4, 46, 41, 18, 14],
       [18, 13, 51, 47, 72],
       [20, 16, 31, 33, 63],
       [45, 21, 54, 55, 79]])

In [154]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [155]:
arr=np.arange(0,25)

In [156]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [157]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
ranarr=np.random.randint(0,101,10)

In [159]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [160]:
ranarr.max()

99

In [161]:
ranarr.min()

2

In [162]:
ranarr.argmax() #index location

5

In [163]:
ranarr.argmin()

7

In [165]:
ranarr.dtype

dtype('int32')

In [167]:
arr.shape

(25,)

In [168]:
arr=arr.reshape(5,5)

In [169]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [170]:
arr.shape

(5, 5)

In [172]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

## Exercise-Numpy

In [173]:
myarr=np.linspace(0,10,101) #solution

## Indexing and Selection

In [176]:
arr=np.arange(0,11)

In [177]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [178]:
arr[8]

8

In [179]:
arr[1:5]

array([1, 2, 3, 4])

In [180]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [181]:
arr[:5]

array([0, 1, 2, 3, 4])

In [182]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [183]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
arr[0:5] = 100

In [186]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [187]:
arr=np.arange(0,11)

In [188]:
slice_of_arr=arr[0:5]

In [189]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [190]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [191]:
slice_of_arr[:] =99

In [192]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [193]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [194]:
arr_copy=arr.copy()

In [195]:
arr_copy[:]=100

In [196]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [197]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [198]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [199]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [200]:
arr_2d.shape

(3, 3)

In [201]:
arr_2d[0]

array([ 5, 10, 15])

In [202]:
arr_2d[2]

array([35, 40, 45])

In [203]:
arr_2d[1][1]

25

In [204]:
arr_2d[1,1]

25

In [205]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [206]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [207]:
arr=np.arange(1,11)

In [208]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [209]:
arr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [210]:
bool_arr=arr>4

In [211]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [212]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [213]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Operations

In [214]:
arr=np.arange(0,10)

In [215]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [217]:
arr - 2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [218]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [219]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [220]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [221]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
arr / arr

<ipython-input-222-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [223]:
1 /arr

<ipython-input-223-148a20bab727>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 /arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [225]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [226]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [227]:
np.log(arr)

<ipython-input-227-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [228]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
arr.sum()

45

In [230]:
arr.mean()

4.5

In [231]:
arr.max()

9

In [232]:
arr.var()

8.25

In [233]:
arr.std()

2.8722813232690143

In [236]:
arr_2d=np.arange(0,25).reshape(5,5)

In [237]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [238]:
arr_2d.sum()

300

In [239]:
arr_2d.sum(axis=0) #row

array([50, 55, 60, 65, 70])

In [240]:
arr_2d.sum(axis=1) #column

array([ 10,  35,  60,  85, 110])